### ISSUE TITLE
Refork Repo

### ISSUE THREAD

**Issue by om3ga6400** [JustSpaceisded/JustSpaceisded5#1]
Since you un-forked my repo, i cannot make pull requests please re-fork for new updates

**Comment by om3ga6400** [comment]
Also the demon image is corrupt

**Comment by om3ga6400** [comment]
@Progamer1251718 fork it from here:https://github.com/OMEGA6404/OMEGA6404/tree/Bambi

**Comment by JustSpaceisded** [comment]
page not found

**Comment by JustSpaceisded** [comment]
BOZO

**Comment by JustSpaceisded** [comment]
@OMEGA6404 
BOZOOOOOOOOOOOOOOOOOOO
