### ISSUE TITLE
look at my profile 

### ISSUE THREAD

**Issue by om3ga6400** [JustSpaceisded/JustSpaceisded5#12]
new discord status thing and look at trophy
![image](https://github.com/Progamer1251718/Progamer1251718/assets/98067930/91ab6d2f-6abc-4d8e-8884-3eedac160597)

**Comment by om3ga6400** [comment]
also private sever for Github Stats thing and Streak Stats

**Comment by om3ga6400** [comment]
i pro githuber

**Comment by om3ga6400** [comment]
@Progamer1251718

**Comment by JustSpaceisded** [comment]
k?
