### ISSUE TITLE
Wrong code 

### ISSUE THREAD

**Issue by om3ga6400** [JustSpaceisded/JustSpaceisded5#2]
<p align="center"> <img src="https://img.shields.io/badge/Discord-Bambi you bozo__%232707-red/?logo=discord&color=7289DA" alt="Progamer1251718" /> </p>
<p align="center">
    <img alt="GitHub Sponsors" src="https://img.shields.io/github/sponsors/Progamer1251718?label=Sponsors&logo=githubsponsors">
    <img alt="GitHub User's stars" src="https://img.shields.io/github/stars/Progamer1251718?color=yellow&label=User%20Stars&logo=github&logoColor=yellow">
    <img src="https://komarev.com/ghpvc/?username=Progamer1251718" alt="Progamer1251718"/>       
     
      
     
    <a href="https://github.com/Progamer1251718/Progamer1251718/pulse" alt="Activity"><img src="https://img.shields.io/github/commit-activity/m/Progamer1251718/Progamer1251718" /></a>
    <a href="https://github.com/Progamer1251718?tab=followers"><img alt="Followers" src="https://img.shields.io/github/followers/OMEGA6404?color=4C1&logo=github"></a>
    <a href="https://github.com/Progamer1251718/Progamer1251718" target="_blank"><img alt="Profile_Update" src="https://img.shields.io/github/last-commit/OMEGA6404/OMEGA6404?label=Profile%20update&style=fflat-square"></a>
    
    
    
</p> 
These are my stats at least change the name

**Comment by om3ga6400** [comment]
The last 2 are my stats

**Comment by JustSpaceisded** [comment]
nop u got way more followers

**Comment by JustSpaceisded** [comment]
fixed
