### ISSUE TITLE
Refork Repo

### ISSUE THREAD

**Issue by om3ga6400** [JustSpaceisded/JustSpaceisded5#7]
Since you un-forked my repo, i cannot make pull requests please re-fork for new updates here:https://github.com/OMEGA6405/OMEGA6405/tree/Bambi

**Comment by JustSpaceisded** [comment]
why u said no copy

**Comment by JustSpaceisded** [comment]
so?

**Comment by JustSpaceisded** [comment]
ill ask u on discord omeg

**Comment by JustSpaceisded** [comment]
closing
