### ISSUE TITLE
Wrong stats for snk

### ISSUE THREAD

**Issue by om3ga6400** [JustSpaceisded/JustSpaceisded5#8]
Your snake stats thing it just mine host it on you profile

**Comment by om3ga6400** [comment]
@Progamer1251718

**Comment by JustSpaceisded** [comment]
wdym

**Comment by om3ga6400** [comment]
@Progamer1251718 see its not yours 
![image](https://user-images.githubusercontent.com/98067930/235206034-48f32e93-8f04-4259-8a2c-41ec31b645bf.png)

**Comment by om3ga6400** [comment]
platane/platane

**Comment by om3ga6400** [comment]
not programmer

**Comment by JustSpaceisded** [comment]
br

**Comment by JustSpaceisded** [comment]
i remove
